### ISSUE TITLE
Log in with GitHub-based GBIF account

### ISSUE THREAD

**Issue by wkmor1** [gbif/metabarcoding-data-toolkit-ui#139]
Unlike gbif.org a user cannot currently authenticate with a GitHub account (and presumbly Orcid or Google).
Note that a GitHub _connected_ account can log in but an account without an explicit GBIF password currently cannot.

**Comment by thomasstjerne** [comment]
This will unfortunately not be possible since this would mean we should share the GBIF app token for GitHub with all MDT installations. In the future, there might be such installations running outside GBIF servers.

We could make it clear in the login form, that users will need a password for their user account.

**Comment by wkmor1** [comment]
Ok fair enough. Yeah some indication that it wont work somewhere in the UI might be good. It tripped me up initially, but I had another GBIF account I could use instead. And maybe a link to some docs that explain how to add a GBIF password to an account (if this is possible?).
